# Generated by Django 6.0.2 on 2026-03-03 22:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_add_expo_push_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='connectivity_mode',
            field=models.CharField(choices=[('auto', 'Auto (P2P with relay fallback)'), ('p2p', 'Always P2P'), ('server', 'Always Server (relay)')], default='auto', help_text='WebRTC call connection mode preference', max_length=10),
        ),
    ]
