# Generated by Django 5.2.4 on 2026-06-02 01:24

import users.db_storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_profile_extras'),
    ]

    operations = [
        migrations.CreateModel(
            name='FileBlob',
            fields=[
                ('name', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('data', models.BinaryField()),
                ('content_type', models.CharField(blank=True, default='', max_length=120)),
                ('size', models.PositiveIntegerField(default=0)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AlterField(
            model_name='blockeduser',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.ImageField(blank=True, null=True, storage=users.db_storage.DatabaseStorage(), upload_to='avatars/'),
        ),
    ]
