# Generated by Django 5.2.4 on 2026-06-18 22:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_rename_userdevice_indexes'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdevice',
            name='fcm_token',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddIndex(
            model_name='userdevice',
            index=models.Index(fields=['fcm_token'], name='users_userd_fcm_tok_380865_idx'),
        ),
    ]
