# Generated by Django 6.0.2 on 2026-09-09 15:10

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0017_userpresencesession_installation_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='SignInChallenge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('challenge_id', models.UUIDField(default=uuid.uuid4, unique=True)),
                ('code_hash', models.CharField(blank=True, max_length=255)),
                ('expires_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('last_sent_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('window_started_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('send_count', models.PositiveSmallIntegerField(default=0)),
                ('attempts', models.PositiveSmallIntegerField(default=0)),
                ('consumed', models.BooleanField(default=True)),
                ('google_subject', models.CharField(blank=True, max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='GoogleIdentity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=255, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='google_identity', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
