# Generated by Django 6.0.2 on 2026-06-08 01:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calls', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='calllog',
            name='invite_acked_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='calllog',
            name='push_sent_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='calllog',
            name='ws_notified_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
