# Generated by Django 6.0.2 on 2026-07-07 15:43

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0006_messagedelivery_routing_metadata'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MediaBlob',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('message_id', models.CharField(blank=True, default='', max_length=64)),
                ('media_type', models.CharField(choices=[('image', 'Image'), ('voice', 'Voice'), ('video', 'Video')], max_length=16)),
                ('mime', models.CharField(max_length=80)),
                ('size_bytes', models.PositiveIntegerField()),
                ('sha256', models.CharField(db_index=True, max_length=64)),
                ('duration_ms', models.PositiveIntegerField(blank=True, null=True)),
                ('width', models.PositiveIntegerField(blank=True, null=True)),
                ('height', models.PositiveIntegerField(blank=True, null=True)),
                ('data', models.BinaryField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('all_confirmed_at', models.DateTimeField(blank=True, null=True)),
                ('delete_after', models.DateTimeField(blank=True, null=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='uploaded_media', to=settings.AUTH_USER_MODEL)),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='media_blobs', to='chat.chatroom')),
            ],
        ),
        migrations.CreateModel(
            name='MediaDownload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('installation_id', models.CharField(blank=True, default='', max_length=128)),
                ('verified_at', models.DateTimeField(auto_now_add=True)),
                ('media', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='downloads', to='chat.mediablob')),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='media_downloads', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddIndex(
            model_name='mediablob',
            index=models.Index(fields=['delete_after'], name='chat_mediab_delete__f84ce4_idx'),
        ),
        migrations.AddIndex(
            model_name='mediablob',
            index=models.Index(fields=['created_at'], name='chat_mediab_created_85c24b_idx'),
        ),
        migrations.AddIndex(
            model_name='mediablob',
            index=models.Index(fields=['room', 'owner'], name='chat_mediab_room_id_40c1e6_idx'),
        ),
        migrations.AddIndex(
            model_name='mediadownload',
            index=models.Index(fields=['media', 'recipient'], name='chat_mediad_media_i_8b14a6_idx'),
        ),
        migrations.AddConstraint(
            model_name='mediadownload',
            constraint=models.UniqueConstraint(fields=('media', 'recipient', 'installation_id'), name='uniq_media_download_per_device'),
        ),
    ]
