# Generated by Django 6.0.2 on 2026-07-07 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0007_mediablob_mediadownload_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='mediablob',
            name='md5',
            field=models.CharField(blank=True, default='', max_length=32),
        ),
    ]
