# Generated by Django 6.0.2 on 2026-08-21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0008_mediablob_md5'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mediablob',
            name='media_type',
            field=models.CharField(
                choices=[
                    ('image', 'Image'),
                    ('voice', 'Voice'),
                    ('video', 'Video'),
                    ('document', 'Document'),
                ],
                max_length=16,
            ),
        ),
    ]
