# Generated by Django 6.0.2 on 2026-08-21 19:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0011_groupmembership'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='groupmembership',
            new_name='chat_groupm_room_id_d6bb7c_idx',
            old_name='chat_groupm_room_id_3ee1c8_idx',
        ),
        migrations.RenameIndex(
            model_name='offlineemailnudge',
            new_name='chat_offlin_recipie_ab28dc_idx',
            old_name='chat_nudge_recipient_idx',
        ),
    ]
